language: smalltalk
sudo: false

os:
  - linux

smalltalk:
  - Pharo-7.0

# Unit tests run the normal pillar tests
# Integration tests test that pillar itself can interact with generated files, pdf generation, etc.
# System tests test that we can install and use pillar as a black box
env:
  matrix:
  - JOB=test TYPE=System ARCHETYPE=book OUTPUT=pdfs

install:
  # Pillar installation
  - git clone https://github.com/pillar-markup/pillar.git -b v7.4.1 # Clone pillar before worked with dev-7 
  - cd pillar && ./scripts/build.sh && cd ..                              # Run pillar build script. Pillar will be built in `pwd`/build!
  - . pillar/scripts/ci/ensure_latex.sh                                   # Install latex
  - ./pillar/scripts/ci/ensure_book_dependencies.sh                       # Install latex dependencies required by pillar
  
script:
  - ./pillar/build/pillar build pdf

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - mv _result/pdf/learningoop.pdf learningoop-wip.pdf
  - bash upload.sh learningoop-wip.pdf

branches:
  except:
    - /^(?i:continuous)$/
