language: smalltalk
sudo: false

os:
  - linux

smalltalk:
  - Pharo64-7.0

env:
  global:
    - PILLAR_RELEASE=v8.0.0
    - PATH="$HOME/texlive/bin/x86_64-linux:$HOME/pillar/build:$PATH"

install:
  - git clone --branch "$PILLAR_RELEASE" https://github.com/pillar-markup/pillar.git "$HOME/pillar"
  - ( cd $HOME/pillar; ./scripts/build.sh; )
  - $HOME/pillar/scripts/ci/install-texlive
  - ./_support/latex/ensure-deps.sh

script:
  - pillar build pdf

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - mv _result/pdf/learningoop.pdf learningoop-wip.pdf
  - bash upload.sh learningoop-wip.pdf

branches:
  except:
    - /^(?i:continuous)$/
